// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package demo

import (
	"github.com/google/wire"
	"ultra-hand/pkg/config"
	"ultra-hand/pkg/log"
)

// Injectors from wire.go:

func InitGrpcDemo(cp config.Path) (Demo, error) {
	viper, err := config.New(cp)
	if err != nil {
		return Demo{}, err
	}
	option, err := log.NewLoggerOption(viper)
	if err != nil {
		return Demo{}, err
	}
	sugaredLogger, err := log.NewZapLogger(option)
	if err != nil {
		return Demo{}, err
	}
	logger, err := log.New(option, sugaredLogger)
	if err != nil {
		return Demo{}, err
	}
	demo := New(logger)
	return demo, nil
}

// wire.go:

var ProvideSet = wire.NewSet(
	DemoProvideSet, log.ProvideSet, config.ProvideSet,
)
