log:
  loggerName: Default
  logPath: D:\\开发\\ultra-hand\\tmp\\demo.log
  errLogPath: D:\\开发\\ultra-hand\\tmp\\err.log
  levelEnabler: debug
  stdout: true
  json: false
  maxSizeMB: 10
  maxBackups: 3
  maxAgeDay: 3
  compress: false
  timeRotate: true
  rotationHour: 1